# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{etree}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Barry"]
  s.date = %q{2010-06-14}
  s.description = %q{A port of the perl scripts found at http://etree-scripts.sourceforge.net}
  s.email = %q{mail@paulbarry.com}
  s.executables = ["flac2mp3", "parse_info"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "Rakefile",
     "VERSION",
     "lib/etree.rb",
     "test/helper.rb",
     "test/test_etree.rb"
  ]
  s.homepage = %q{http://github.com/pjb3/etree}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Scripts for working with flac files posted to http://bt.etree.org}
  s.test_files = [
    "test/helper.rb",
     "test/test_etree.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<chronic>, ["= 0.2.3"])
      s.add_runtime_dependency(%q<escape>, ["= 0.0.4"])
    else
      s.add_dependency(%q<chronic>, ["= 0.2.3"])
      s.add_dependency(%q<escape>, ["= 0.0.4"])
    end
  else
    s.add_dependency(%q<chronic>, ["= 0.2.3"])
    s.add_dependency(%q<escape>, ["= 0.0.4"])
  end
end

